import {
  BrainCircuit,
  ShieldAlert,
  BadgeCheck,
  CheckCircle2,
} from "lucide-react";

import { useInsights } from "../../hooks/useInsights";

type AIInsight = {
  summary: string;
  risk: string;
  confidence: number;
  recommendations: string[];
};

export default function AIInsights() {
  const { data, isLoading, isError } = useInsights();

  if (isLoading) {
    return (
      <div className="rounded-3xl bg-white border shadow-sm p-8">
        Loading AI Insights...
      </div>
    );
  }

  if (isError || !data) {
    return (
      <div className="rounded-3xl bg-white border shadow-sm p-8">
        Failed to load AI Insights.
      </div>
    );
  }

  const insight = data as AIInsight;

  const riskColor =
    insight.risk === "High"
      ? "bg-red-100 text-red-600"
      : insight.risk === "Medium"
      ? "bg-yellow-100 text-yellow-700"
      : "bg-green-100 text-green-600";

  return (
    <div className="rounded-3xl overflow-hidden shadow-xl">

      {/* Header */}

      <div className="bg-gradient-to-r from-indigo-600 via-blue-600 to-cyan-500 text-white p-6">

        <div className="flex items-center gap-4">

          <div className="bg-white/20 p-4 rounded-2xl">

            <BrainCircuit size={34} />

          </div>

          <div>

            <h2 className="text-2xl font-bold">
              HospitalIQ AI
            </h2>

            <p className="text-blue-100">
              Executive Intelligence
            </p>

          </div>

        </div>

      </div>

      {/* Body */}

      <div className="bg-white p-6">

        <div className="mb-6">

          <p className="text-slate-700 leading-7">

            {insight.summary}

          </p>

        </div>

        {/* Risk */}

        <div className="flex justify-between items-center mb-6">

          <div className="flex items-center gap-3">

            <ShieldAlert className="text-slate-500" />

            <span className="font-medium">
              Risk Level
            </span>

          </div>

          <span
            className={`px-4 py-2 rounded-full font-semibold ${riskColor}`}
          >
            {insight.risk}
          </span>

        </div>

        {/* Confidence */}

        <div className="flex justify-between items-center mb-6">

          <div className="flex items-center gap-3">

            <BadgeCheck className="text-slate-500" />

            <span className="font-medium">
              AI Confidence
            </span>

          </div>

          <span className="font-bold text-indigo-600">

            {insight.confidence}%

          </span>

        </div>

        {/* Recommendations */}

        <div>

          <h3 className="font-semibold text-lg mb-4">

            Recommendations

          </h3>

          <div className="space-y-3">

            {insight.recommendations.map(
              (item, index) => (
                <div
                  key={index}
                  className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 hover:bg-slate-100 transition"
                >
                  <CheckCircle2
                    className="text-green-500"
                    size={20}
                  />

                  <span>{item}</span>

                </div>
              )
            )}

          </div>

        </div>

        <div className="mt-6 pt-5 border-t text-xs text-slate-400">

          Generated by HospitalIQ AI • Just now

        </div>

      </div>

    </div>
  );
}